version: "2.3"

services:
  website:
    image: ewoutvdb/gui-website
    container_name: 'gui-website'
    networks:
      - frontend
    ports:
      - 80:80
    links:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  api:
    image: ewoutvdb/gui-api
    container_name: 'gui-api'
    environment:
      DATABASE_URL: postgres://postgres:toor123@db:5432/postgres
      JWT_SECRET: 'toor123'
      HOST: '::'
      PORT: 80
      RUST_LOG: 'axum_jwt_login=info,server=info,sqlx::query=error,tower_http=info,info'
    networks:
      - frontend
      - backend
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: 'gui-db'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: toor123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - backend
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  frontend:
  backend:
